name: Build and Release Extension

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Chrome extension
        run: |
          cp src/manifest.chrome.json src/manifest.json
          cd src
          zip -r ../doom-tasks-chrome.zip . -x "*.git*" "manifest.*.json" "assets/*" "README.md"
          cd ..

      - name: Build Firefox extension
        run: |
          cp src/manifest.firefox.json src/manifest.json
          cd src
          zip -r ../doom-tasks-firefox.zip . -x "*.git*" "manifest.*.json" "assets/*" "README.md"
          cd ..

      - name: Upload Chrome extension ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: doom-tasks-chrome.zip
          asset_name: doom-tasks-chrome.zip
          asset_content_type: application/zip

      - name: Upload Firefox extension ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: doom-tasks-firefox.zip
          asset_name: doom-tasks-firefox.zip
          asset_content_type: application/zip
